# Application configuration
app:
  title: "QuantDash - Algorithmic Trading Dashboard"
  debug: true
  port: 8050
  host: "127.0.0.1"

# Data configuration
data:
  default_ticker: "SPY"
  default_period: "5y"
  data_source: "yahoo"
  cache_enabled: true
  cache_duration: 3600  # seconds

# Backtesting configuration
backtesting:
  initial_cash: 100000
  commission: 0.001  # 0.1%
  slippage: 0.0005   # 0.05%

# Dashboard configuration
dashboard:
  theme: "bootstrap"
  default_charts:
    - "price_chart"
    - "equity_curve"
    - "drawdown"
  default_metrics:
    - "total_return"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "win_rate"
