# Strategy configuration in YAML format
strategies:
  ma_crossover:
    name: "Moving Average Crossover"
    description: "Simple moving average crossover strategy"
    params:
      fast_period: 10
      slow_period: 30
    
  rsi_pullback:
    name: "RSI Pullback"
    description: "Buy oversold, sell overbought with trend filter"
    params:
      rsi_period: 14
      oversold: 30
      overbought: 70
      sma_period: 200
      stop_loss: 0.03
    
  bollinger_breakout:
    name: "Bollinger Band Breakout"
    description: "Trade breakouts from Bollinger Bands"
    params:
      period: 20
      std_dev: 2
    
  dual_momentum:
    name: "Dual Momentum"
    description: "Absolute and relative momentum strategy"
    params:
      lookback_period: 252  # 12 months
      rebalance_frequency: "monthly"
    
  gap_fade:
    name: "Gap Fade"
    description: "Mean reversion on overnight gaps"
    params:
      gap_threshold: 0.01
      profit_target: 0.005
    
  pair_trading:
    name: "Pair Trading"
    description: "Statistical arbitrage on correlated pairs"
    params:
      lookback_period: 60
      entry_zscore: 2.0
      exit_zscore: 0.0
    
  turtle_breakout:
    name: "Turtle Breakout"
    description: "Channel breakout with ATR position sizing"
    params:
      entry_period: 20
      exit_period: 10
      atr_period: 14
